const tintColorLight = '#0a7ea4';
const tintColorDark = '#ffffff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#ffffff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    primary: '#0a7ea4',
    secondary: '#E1F5FE',
    accent: '#FF5722',
    border: '#E0E0E0',
    cardBackground: '#F8F9FA',
    buttonBackground: '#0a7ea4',
    buttonText: '#ffffff',
    error: '#D32F2F',
    success: '#388E3C',
    warning: '#FFA000',
    highlight: '#FFF8E1',
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    primary: '#ffffff',
    secondary: '#263238',
    accent: '#FF7043',
    border: '#424242',
    cardBackground: '#1E1E1E',
    buttonBackground: '#ffffff',
    buttonText: '#0a7ea4',
    error: '#EF5350',
    success: '#66BB6A',
    warning: '#FFCA28',
    highlight: '#37474F',
  },
};
